import { User, UserRole, Team, Event, Report, AppNotification, VisibilitySettings, EventCategory, EventStatus } from './types.ts';

export const INITIAL_MOCK_USERS: { [id: string]: User } = {
  '1': { id: '1', name: 'Admin User', email: 'admin@sims.com', role: UserRole.ADMIN, avatar: 'https://i.pravatar.cc/150?u=1', firstName: 'Admin', lastName: 'User', studentId: 'ADMIN-001', teamId: 't5', password: 'password', lastActive: new Date().toISOString() },
  '2': { id: '2', name: 'Officer Jones', email: 'officer@sims.com', role: UserRole.OFFICER, avatar: 'https://i.pravatar.cc/150?u=2', firstName: 'Jessica', lastName: 'Jones', studentId: 'OFF-002', teamId: 't5', interestedEvents: ['Joker Flag Wave 1: Chant'], password: 'password', lastActive: new Date(Date.now() - 3600000).toISOString() },
  '3': { id: '3', name: 'John Doe', email: 'user@sims.com', role: UserRole.USER, avatar: 'https://i.pravatar.cc/150?u=3', teamId: 't1', firstName: 'John', lastName: 'Doe', studentId: '2023-1005', yearLevel: '2nd Year', section: 'Section 1', interestedEvents: ['Hackathon', 'Essay Writing (English)', 'General Quiz'], bio: 'Loves coding and chess.', password: 'password', lastActive: new Date(Date.now() - 86400000).toISOString() },
  '4': { id: '4', name: 'Leo Leaderson', email: 'lead@sims.com', role: UserRole.TEAM_LEAD, avatar: 'https://i.pravatar.cc/150?u=4', teamId: 't1', firstName: 'Leo', lastName: 'Leaderson', studentId: '2022-1100', yearLevel: '3rd Year', section: 'International', interestedEvents: ['Basketball (Men)', 'Debate', 'Larong Lahi: Tug of War'], bio: 'Competitive and always aiming for the gold!', password: 'password', lastActive: new Date(Date.now() - 60000).toISOString() },
  '5': { id: '5', name: 'Sarah Scribe', email: 'secretary@sims.com', role: UserRole.USER, avatar: 'https://i.pravatar.cc/150?u=5', teamId: 't1', firstName: 'Sarah', lastName: 'Scribe', studentId: '2022-1101', yearLevel: '3rd Year', section: 'International', password: 'password', lastActive: new Date().toISOString() },
  '6': { id: '6', name: 'Timmy Counts', email: 'treasurer@sims.com', role: UserRole.USER, avatar: 'https://i.pravatar.cc/150?u=6', teamId: 't1', firstName: 'Timmy', lastName: 'Counts', studentId: '2022-1102', yearLevel: '3rd Year', section: 'International', password: 'password', lastActive: new Date().toISOString() },
  '7': { id: '7', name: 'Ernie Runner', email: 'errand1@sims.com', role: UserRole.USER, avatar: 'https://i.pravatar.cc/150?u=7', teamId: 't1', firstName: 'Ernie', lastName: 'Runner', studentId: '2023-1006', yearLevel: '2nd Year', section: 'Section 2', password: 'password', lastActive: new Date().toISOString() },
  '8': { id: '8', name: 'Harry Heart', email: 'lead2@sims.com', role: UserRole.TEAM_LEAD, avatar: 'https://i.pravatar.cc/150?u=8', teamId: 't2', firstName: 'Harry', lastName: 'Heart', studentId: '2022-1200', yearLevel: '3rd Year', section: 'Section 1', password: 'password', lastActive: new Date().toISOString() },
  '9': { id: '9', name: 'Chloe Clover', email: 'lead3@sims.com', role: UserRole.TEAM_LEAD, avatar: 'https://i.pravatar.cc/150?u=9', teamId: 't3', firstName: 'Chloe', lastName: 'Clover', studentId: '2022-1300', yearLevel: '3rd Year', section: 'Section 2', password: 'password', lastActive: new Date().toISOString() },
  '10': { id: '10', name: 'Danny Diamond', email: 'lead4@sims.com', role: UserRole.TEAM_LEAD, avatar: 'https://i.pravatar.cc/150?u=10', teamId: 't4', firstName: 'Danny', lastName: 'Diamond', studentId: '2022-1400', yearLevel: '3rd Year', section: 'Section 3', password: 'password', lastActive: new Date().toISOString() },
  '11': { id: '11', name: 'Benlor Rivera', email: 'riverabenlor461@gmail.com', role: UserRole.ADMIN, avatar: 'https://i.pravatar.cc/150?u=11', firstName: 'Benlor', lastName: 'Rivera', studentId: 'ADMIN-BEN', teamId: 't5', password: 'password', lastActive: new Date().toISOString() },
};

export const MOCK_LEADERBOARD: Team[] = [
  { rank: 1, id: 't1', name: 'Midnight Spades', score: 1250, wins: 0, losses: 0, playersCount: 0, description: 'Known for their exceptional performance in coding challenges and strategic gameplay.', unitLeader: '4', unitSecretary: '5', unitTreasurer: '6', unitErrands: ['7'], adviser: '1', merits: [], demerits: [], eventScores: [], scoreHistory: [1000, 1250], progressHistory: [{date: '2024-01-01', score: 1000}, {date: '2024-01-02', score: 1250}], detailedProgressHistory: [], placementStats: { first: 1, second: 0, third: 1, fourth: 0, merits: 1, demerits: 0 }, joinRequests: [] },
  { rank: 2, id: 't2', name: 'Scarlet Hearts', score: 1100, wins: 0, losses: 0, playersCount: 0, description: 'A team with a fiery spirit, excelling in high-energy sports and creative competitions.', unitLeader: '8', adviser: '1', merits: [], demerits: [], eventScores: [], scoreHistory: [1000, 1100], progressHistory: [{date: '2024-01-01', score: 1000}, {date: '2024-01-02', score: 1100}], detailedProgressHistory: [], placementStats: { first: 0, second: 2, third: 0, fourth: 0, merits: 0, demerits: 1 }, joinRequests: [] },
  { rank: 3, id: 't3', name: 'Emerald Clovers', score: 950, wins: 0, losses: 0, playersCount: 0, description: 'Lucky and resilient, the Clovers are masters of endurance and teamwork-based events.', unitLeader: '9', adviser: '1', merits: [], demerits: [], eventScores: [], scoreHistory: [1000, 950], progressHistory: [{date: '2024-01-01', score: 1000}, {date: '2024-01-02', score: 950}], detailedProgressHistory: [], placementStats: { first: 0, second: 0, third: 1, fourth: 2, merits: 0, demerits: 0 }, joinRequests: [] },
  { rank: 4, id: 't4', name: 'Glacier Diamonds', score: 800, wins: 0, losses: 0, playersCount: 0, description: 'Cool under pressure, the Diamonds shine in intellectual and precision-based challenges.', unitLeader: '10', adviser: '1', merits: [], demerits: [], eventScores: [], scoreHistory: [1000, 800], progressHistory: [{date: '2024-01-01', score: 1000}, {date: '2024-01-02', score: 800}], detailedProgressHistory: [], placementStats: { first: 0, second: 0, third: 0, fourth: 1, merits: 0, demerits: 0 }, joinRequests: [] },
  { rank: 0, id: 't5', name: 'Amaranth Jokers', score: 0, wins: 0, losses: 0, playersCount: 0, description: 'The facilitating team responsible for organizing and overseeing the events.', facilitators: [{userId: '1', position: 'Governor', roleDescription: 'Overall head of the event', permissions: {canAdd:true, canDelete:true, canPassScores:true, canUpdate:true}}], merits: [], demerits: [], eventScores: [], scoreHistory: [], progressHistory: [], detailedProgressHistory: [], placementStats: { first: 0, second: 0, third: 0, fourth: 0, merits: 0, demerits: 0 } },
];

export const MOCK_EVENTS: Event[] = [
// FIX: Add missing 'judges' property to satisfy the Event type.
  { id: 'jf1', name: 'Joker Flag Wave 1: Chant', category: EventCategory.JOKER_FLAG, officerInCharge: 'Bhenny & Foncee', participantsInfo: 'All members', date: new Date().toISOString(), venue: 'Game Area', description: 'A rhythmic team chant.', mechanics: 'Minimum 1 minute.', criteria: [{name: 'Creativity', description: 'Uniqueness', points: 30}], status: EventStatus.UPCOMING, competitionPoints: 1000, judges: [], results: [] },
// FIX: Add missing 'judges' property to satisfy the Event type.
  { id: 'cit1', name: 'Cheer Dance', category: EventCategory.CIT_QUEST, officerInCharge: 'Yesha', participantsInfo: '10-15 performers', date: new Date(Date.now() + 86400000).toISOString(), venue: 'Gymnasium', description: 'High-energy cheer routine.', mechanics: 'Max 5 minutes.', criteria: [{name: 'Choreography', description: 'Artistry', points: 50}], status: EventStatus.UPCOMING, competitionPoints: 1500, judges: [], results: [] },
// FIX: Add missing 'judges' property to satisfy the Event type.
  { id: 'ms7', name: 'Hackathon', category: EventCategory.MINDSCAPE, officerInCharge: 'Lryn', participantsInfo: '3 representatives', date: new Date(Date.now() - 86400000).toISOString(), venue: 'Computer Lab 1', description: 'Ideate IT solutions.', mechanics: '5 minute pitch.', criteria: [{name: 'Originality', description: 'Uniqueness', points: 40}], status: EventStatus.COMPLETED, competitionPoints: 1200, judges: [], results: [] },
  { id: 'ct3', name: 'Web Design', category: EventCategory.CODING_TECH_CHALLENGES, officerInCharge: 'Lorenz and Foncee', participantsInfo: '4 representatives', date: new Date().toISOString(), venue: 'Computer Lab 1', description: 'Web design competition.', mechanics: '4 hours to complete.', criteria: [{name: 'Design', description: 'Visuals', points: 30}], status: EventStatus.UPCOMING, competitionPoints: 1200, judges: [], results: [] },
];

export const MOCK_REPORTS: Report[] = [
    { id: 'rep1', type: 'report', problemType: 'unsportsmanlike', description: 'Player from Scarlet Hearts was being disrespectful after the match.', submittedBy: '4', timestamp: new Date(Date.now() - 3600000).toISOString(), status: 'pending', offenderName: 'A. Player', offenderTeam: 'Scarlet Hearts' },
    { id: 'rep2', type: 'suggestion', description: 'It would be great to have more water stations available near the outdoor courts.', submittedBy: '3', timestamp: new Date(Date.now() - 86400000).toISOString(), status: 'reviewed', replies: [{id: 'reply1', repliedBy: '1', message: 'Thank you for the suggestion! We are looking into this.', timestamp: new Date().toISOString()}] },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
    { id: 'notif1', title: 'Scores Updated!', message: 'Results for "Hackathon" are in! Check the leaderboard.', link: '/leaderboard', timestamp: new Date().toISOString(), type: 'success' },
    { id: 'notif2', title: 'New Event Added', message: 'A new event "Web Design" has been added to the Cipher Matrix category.', link: '/events', timestamp: new Date(Date.now() - 3600000).toISOString(), type: 'info' },
    { id: 'notif3', title: 'Report Status Changed', message: 'Your suggestion about water stations has been reviewed.', link: '/reports', timestamp: new Date(Date.now() - 7200000).toISOString(), type: 'info', target: { userId: '3' } },
];

export const MOCK_VISIBILITY_SETTINGS: VisibilitySettings = {
  competitionScores: true,
  pages: { dashboard: true, leaderboard: true, teams: true, events: true, rules: true, reports: true, profile: true },
  dashboard: { summaryCards: true, leaderboardRanking: true, topTeams: true, teamScoreProgression: true },
  leaderboard: { tabs: { standings: true, records: true, meritsLog: true } },
  teams: { facilitatingTeam: true, participatingTeams: true, tabs: { overview: true, leadership: true, joinRequests: true, roster: true, prospects: true, progress: true, merits: true, scores: true } },
  events: { categories: { [EventCategory.JOKER_FLAG]: true, [EventCategory.CIT_QUEST]: true, [EventCategory.MINDSCAPE]: true, [EventCategory.HOOP_SPIKE]: true, [EventCategory.CODING_TECH_CHALLENGES]: true, [EventCategory.PIXEL_PLAY]: true, [EventCategory.TABLE_MASTERS]: true } },
  rules: { sections: { objectives: true, house_rules: true, demerit_system: true, complaints: true, scoring_system: true, categories_mechanics: true } },
  reports: { tabs: { view: true, submit: true } },
};